Assignment 01 - Python, NumPy, Matplotlib and Pandas
----------------------------

**Due: Fri 09/09/2016**


**Please fill these in before submitting, just in case I accidentally mix up file names while grading**:

Name: Joe Student

CWID-5: (Last 5 digits of cwid)

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

Problem 1: Python Function
--------------------------

Euclid showed that the greatest common divisor `gcd(m, n)` of two nonnegative integers $m$ and
$n$ satisfies the following mathematical (recursive) definition:

$$
gcd(m, n) = \begin{cases}
    m & \displaystyle \text{if} \quad n = 0 \\
    gcd(n, m \; \text{mod} \; n) & \text{if} \quad n > 0 \\
\end{cases}
$$

Write a Python function, named `gcd`, that implements this mathematical expression to find the
greatest common divisor.  Your function should take two parameters as input, `m` and `n`.
These parameters are assumed to positive (or 0) integers. The `gcd`
function should be a recursive function, it will call itself for cases where $n > 0$  Your 
function will return a single integer value as its result.
 

Here is an example of using the function, and the correct results you should get for several invocations.

    print gcd(108, 192)
    >>> 12
    print gcd(9, 3)
    >>> 3
    print gcd(107, 192) # 107 is prime, so...
    >>> 1

Problem 2: NumPy Operations
---------------------------

For all of the tasks for this problem you are required to use NumPy array operations and library functions exclusively to solve them.  It is
incorrect to use any Python loops or if condition statements to solve these tasks.

Create a (36,) shaped vector called `v`, containing floating point values $1.0, 2.0, 3.0, ..., 36.0$
Using `v` and the `reshape` NymPy function, create arrays called `a` and `b` that are (6,6) two dimensional, and (3, 4, 3) three
dimensional views into v.

Using fancy indexing (no loops, must use NumPy functions/operations), change all odd values of your a array to their negative (e.g. 1 should
be -1, 3, should be -3, etc, but even values are left unchanged), and assign the results back into a.  You might want to, for example,
use the modulus operator (%) to  create an index mask to perform this using fancy indexing.

Now multiply all values in array `a` where $a >= 0$ by $2.5$ and assign the results back into a.

After performing the previous 2 steps on a, the values in a should now be:

    print a
    >>>
    [[ -1.   5.  -3.  10.  -5.  15.]
     [ -7.  20.  -9.  25. -11.  30.]
     [-13.  35. -15.  40. -17.  45.]
     [-19.  50. -21.  55. -23.  60.]
     [-25.  65. -27.  70. -29.  75.]
     [-31.  80. -33.  85. -35.  90.]] 
     
    print a.shape
    >>> (6, 6)

Create a new array, called, c, of random floating point values in the range $0.0 .. 1.0$.  The c array should have 25 rows and 8 columns.
Create a vector called row_min that contains the minimum value for each of the 25 rows (this implies the shape of this vector will be (25,))
Create a vector called col_max that contains the maximum value for each of the 8 columns (col_max will be a vector of shape (8,))

Problem 3: Vectorized Functions and Plotting
--------------------------------------------

The following equations are known as the *deltoid* curve:


$x = 2 \; \text{cos} \; \theta + \text{cos} \; 2 \theta$

$y = 2 \; \text{sin} \; \theta - \text{sin} \; 2 \theta$

Where $0 \le \theta \le 2 \pi$.  Take a set of values of $\theta$ ranging from $0$ to $2\pi$
and calculate $x$ and $y$ from each of the equations above.  Then plot $y$ as a function of $x$.


Problem 4: Pandas
-----------------

There is a file in your repository directory, under the data subdirectory,
called `assg-01-data.csv` formatted using comma separated values.  This file
contains 15 lines of sales data.  Read the data into a `Pandas` data frame simply named `d`, and display the 
first 5 lines of data using the `head()`
member function.  Display the last 5 lines of the data using the `tail()` member function.

As you should be able to see, the data consists of some customer sales' information, along with the customer address.  
The data contains sales information for 3 months.

In the next cell, create a new column in your `Pandas` data frame named `total`.  This column should contain the total
sales for each row for the 3 months of data present.

Using pandas data frame operations only, find out the following information:

- The total sum of sales in the month of Jan
- The minimum sales amount in the month of Feb
- The average (mean) sales for the month of Mar

In the next cell, create a dataframe called `d2` that only contains rows of data in d that don't have any missing (`NaN`) values.

Determine which rows in `d` contain missing data.  There are several ways to do this using `Pandas` operations.  You can find
the missing rows in the differences between d and d2.  Or you can use the `isnull()` and `any()` member functions in combination
to create an index filter of those indexes that have any value that is missing.  Do this in the next cell, and remember to only
use valid `Pandas` operations to find out the answer.