Python
======

In [1]:
from IPython.core.display import Image 
Image(url='http://imgs.xkcd.com/comics/python.png') 

Variables and Operators
-----------------------

Python is a high-level, interpreted language.  Python has become very popular all the way from learning basic beginning programming up to enterprise level software and web systems development.  Of importance to this class, Python is being used extensively by computational scientists for scientific programming, machine learning and high performance computing tasks and environments.  Lets start with the obligatory hello world program:

In [2]:
print("Hello World")

Hello World


Like many interpreted languages, Python does not require that variable types be declared before use.  The type of the 
variable is determined by the value that is assigned to the variable.  Compare this to languages like C and Java (typed
languages) that require that the types of all variables be declared before use, known by the compiler, and are strictly enforced.

Here are some examples of defining and using variables of different types, with a few simple operators applied to 
the variables of different types.

In [3]:
# some integers
x = 1
y = x + 5
print 'x = ', x
print 'y = ', y
print type(x)

x =  1
y =  6
<type 'int'>


In [4]:
# variables can be strings in Python
msg1 = 'And now for something'
print msg1
msg2 = 'completely different'
print msg1 + ' ' + msg2
print (msg1 + '--') * 2
print type(msg1)

And now for something
And now for something completely different
And now for something--And now for something--
<type 'str'>


In [5]:
# floating point numbers, of course, are supported
pi = 3.141592653587932
radius = 3
area = pi * radius ** 2.0
print "area of circle with radius =  %f is %f" % (radius, area)
print type(pi)

area of circle with radius =  3.000000 is 28.274334
<type 'float'>


Functions 
---------

A function is a named sequence of statements that performs a computation.  Functions are important for breaking large 
problems up into small chunks that we can manageably implement.

Functions can take *arguments* also called *parameters* as input.  A function in python always returns a value, but if 
you don't specify the value to return using the **return** keyword, it returns the special value **None**.  For those 
paying attention, we have already seen an example of a function call when we invoked the built in `type()` function previously.

In [6]:
def print_lyrics():
    print "I'm a lumberjack, and I'm okay."
    print "I sleep all night and I work all day."

Notice when you define a function, it doesn't actually execute anything.  In order to execute a function, you need to invoke it.

In [7]:
print_lyrics()

I'm a lumberjack, and I'm okay.
I sleep all night and I work all day.


The previous function neither accepted any input arguments, nor returned any values.  All of the work it performed 
caused only side effects to occur, in this case sending some strings to the standard output.  Here is a function that 
takes input parameters, performs some work, and then returns a value.

In [8]:
def calculate_area_of_circle(radius):
    area = pi * radius ** 2.0
    return area

radius = 5.0
area = calculate_area_of_circle(radius)
print "The area of a circle with radius %f is %f" % (radius, area)

The area of a circle with radius 5.000000 is 78.539816


Built in Data Structures
------------------------

Python has many powerful built in fundamental data structures.  I will only quickly introduce 3 important ones here: lists, tuples and dicts.


** Lists **

Lists are used to contain a sequence of values.  Lists are mutable, which means their contents can be changed after they are created.  The values in a list can be of different types (which is one important way lists are fundamentally different from C and Java arrays).  Lists are indicated syntatically in Python using the square brackets [ and ].

Some examples of defining lists.

In [9]:
cheeses = ['Cheddar', 'Edam', 'Gouda']
numbers = [17, 123, 42]
empty = []
print cheeses

['Cheddar', 'Edam', 'Gouda']


Lists can be nonhomogeneous, e.g. contain values of different types.

In [10]:
l = ['spam', 2.0, 5, 'Gouda', None, 3.14159]
print l

['spam', 2.0, 5, 'Gouda', None, 3.14159]


Lists can be nested, to create complex hierarchies of information.

In [11]:
nested = [1, 4, [2, 8], 9, [3, 5, 7, [9, 2]]]
print nested

[1, 4, [2, 8], 9, [3, 5, 7, [9, 2]]]


Lets actually use the lists and access the values.  Here we show how to access individual items, as well as multiple items known as list slices.

Items are indexed starting at 0, as in C based languages (C, C++, Java, C#, etc.)

In [12]:
# using the cheeses list we created in a previous cell
print cheeses[2] # the item at index 2 is actually the 3rd item in the list
print cheeses[0] # the initial item is at index 0

Gouda
Cheddar


We can use negative indexes to find items relative to the end of the list.

In [13]:
# here again we are using the list called l, defined above in a previous cell, to access the 3rd item from the end
print l[-3]
# this implies -1 always refers to the last item in the list
print l[-1]

Gouda
3.14159


We can use slices to access parts or multiple values of a list.  Notice that the result of slicing a list is a new list.

In [14]:
print l[1:3]

[2.0, 5]


Lists are **mutable**.  We can change particular items, add/insert and remove items.

In [15]:
cheeses.append('Swiss')
print cheeses
cheeses.remove('Edam')
print cheeses
cheeses[1] = 'Camembert'
print cheeses

['Cheddar', 'Edam', 'Gouda', 'Swiss']
['Cheddar', 'Gouda', 'Swiss']
['Cheddar', 'Camembert', 'Swiss']


**Dictionaries**

Dictionaries are very useful fundamental data types, and you will see them used extensively in Python programming.  Dictionaries are also 
known as hash tables or maps in other contexts.  Like a list, a dictionary maps a key to a particular value.  But lists always map an 
integer index/key to a particular value.  A dictionary allows you to map any arbitrary key to a value.  Python uses curley 
braces `{` and `}` syntatically to indicate dictionary data structuers.

An example should make this clearer.

In [16]:
birthday = {'Newton': 1642,
            'Darwin': 1809,
            'Curie': 1867,
            'Einstein': 1879}
print "Newton was born in the year", birthday['Newton']
print "Madame Curie was born in the year", birthday['Curie']

Newton was born in the year 1642
Madame Curie was born in the year 1867


Dictionaries are also mutable, we can add and remove from them after being created.

In [17]:
birthday['Turing'] = 1912
print birthday
del birthday['Darwin']
print birthday

{'Curie': 1867, 'Newton': 1642, 'Darwin': 1809, 'Turing': 1912, 'Einstein': 1879}
{'Curie': 1867, 'Newton': 1642, 'Turing': 1912, 'Einstein': 1879}


Finally I will mention tuples as you will see them used a lot in Python coding examples.  You can think of a tuple simply as an **immutable** list, e.g. one that cannot be changed after it is created.  The ( and ) parenthesis are used syntatically in Python to indicate an immutable tuple.  Notice here that if we create an immutable list `t`, then try to assign a new value to one of the elements, we generate a TypeError
exception.  This is because immutable objects cannot be changed, thus assignment like this is illegal.

In [18]:
t = ('a', 'b', 'c', 'd', 'e')
print t[2]

c


In [19]:
t[3] = 'x'

TypeError: 'tuple' object does not support item assignment

One useful convention/pattern you will run across in Python coding is returning tuples from functions.  If you create a function that needs to return more than one value, you can return a tuple.

In [20]:
def divide(x, y):
    """Integer division of the x (dividend) by y (divisor).
    We expect x and y to be integers.
    Return both the result (quotient) and the remainder"""
    quotient = x / y
    remainder = x % y
    return (quotient, remainder)

(q, r) = divide(22, 7)
print 'Result of dividing 22 / 7 is %d with a remainder of %d' % (q, r)

Result of dividing 22 / 7 is 3 with a remainder of 1


Notice that, since the function returns a tuple with 2 values, we need to assign the result of calling the function back into a tuple 
with two variables.  In other words, since the `divide()` functions returns a tuple with 2 values, those 2 values are assigned
into the variables `q` and `r` when returned from the function above.

The divide function above is actually a reimplementation of the built-in divmod() Python function.  Notice that divmod() returns a tuple as well.

In [21]:
help(divmod)

Help on built-in function divmod in module __builtin__:

divmod(...)
    divmod(x, y) -> (quotient, remainder)
    
    Return the tuple (x//y, x%y).  Invariant: div*y + mod == x.



In [22]:
(q, r) = divmod(22, 7)
print 'Result of dividing 22 / 7 is %d with a remainder of %d' % (q, r)

Result of dividing 22 / 7 is 3 with a remainder of 1


Conditions and Iterations
-------------------------

We wouldn't be able to do much computing if we could only list a sequence of instructions that needed to be executed. Besides
functions we also use conditional execution of code (**if**, **else**) and  looping to execute a block of 
statements multiple times (**for**, **while**)

Python supports boolean **True**, and **False** as a built in data type.

In [23]:
print 3 == 5
print 2 < 4
b = True
type(b)

False
True


bool

We can build conditional execution statements using boolean or logical expressions.  You should try the following cell with even and odd
integer values of `x`.  Do you understand what the `%` operator does, and how this conditional statement works?

In [24]:
x = 33
if x % 2 == 0:
    print 'x is even'
else:
    print 'x is odd'

x is odd


Python contains no switch/case chained conditional (as in C's  `switch` / `case` chained blocks), instead in Python we
use if, elseif, else blocks.

Here is an example.  Write a function tat takes as argument an integer x and returns f(x), f being defined as:

$$
f(x) = \begin{cases}
    \text{Not Defined} & \text{for} \quad x < 1 \\\\ 
    1 & \text{for} \quad x = 1 \\\\
    3 & \text{for} \quad x = 2 \\\\
    f(x-1) * f(x-2) + f(x-1)~~~~& \text{for} \quad x > 2 \\\\
\end{cases}
$$

In [25]:
def f(x):
    if x < 1:
        return None
    elif x == 1:
        return 1
    elif x == 2:
        return 3
    else:
        return f(x-1) * f(x-2) + f(x-1)
    
print f(-3)
print f(5)

None
168


The while statement is available for variable controlled loops, but by far the **for x in y** pattern is used much more commonly in Python
in order to iterate over the elements of a list or dictionary.  Two quick examples.

In [26]:
# assuming cheeses is still defined from previous cells
for c in cheeses:
    print "Here is a cheese: ", c

# ditto, we are using the birthday dictionary from above here
for scientist, byear in birthday.items():
    print "%s was born in year %d" % (scientist, byear)

Here is a cheese:  Cheddar
Here is a cheese:  Camembert
Here is a cheese:  Swiss
Curie was born in year 1867
Newton was born in year 1642
Turing was born in year 1912
Einstein was born in year 1879


Libraries
=========

Python has a large collection of [standard libraries](http://docs.python.org/2/library/index.html).  For example to use the math and random standard libraries, we do the following.

In [27]:
from IPython.display import HTML
HTML('<iframe src=http://docs.python.org/2/library/index.html width=700 height=350></iframe>')

In [28]:
import math
import random

# generate random number between 1 and 10
r = random.randint(1, 10)

def area(r):
    return math.pi * math.pow(r, 2.0)

print r, area(r)

5 78.5398163397



NumPy
-----

The **NumPy** library provides multi-dimensional arrays (e.g. vectors, matrices, ...).  NumPy arrays are more similar to arrays in C and Java than the list data type, specifically because all of the elements in the NumPy array must be of the same type, and they are stored  as a single block of contiguously allocated memory.  By default, if you don't specify the type of the NumPy array being created, NumPy assumes you want to use floats.

NumPy by convention is usually referred to using the shorthand module name `np`:

In [29]:
import numpy as np

In [30]:
v = np.zeros(3)
M = np.ones((3,4))
A = np.array([[1,2,3],[4,5,6]]) 
print "v\n", v
print "M\n", M
print "A\n", A

v
[ 0.  0.  0.]
M
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
A
[[1 2 3]
 [4 5 6]]


You can also work with sub-matrices in a similar fashion as in MatLab, but starting with index 0:

In [31]:
print A
print "the first column of A:", A[:,0]
print "the first    row of A:", A[0,:]

[[1 2 3]
 [4 5 6]]
the first column of A: [1 4]
the first    row of A: [1 2 3]


In [32]:
x = np.arange(10)
print x

[0 1 2 3 4 5 6 7 8 9]


In [33]:
y = np.random.uniform(size=10) # note the named argument here. The 1st (default) arguments are 0 and 1.
print y

[ 0.7667224   0.53001939  0.37673469  0.79292462  0.66453864  0.56310801
  0.41145986  0.20866002  0.9338029   0.50673912]


Matplotlib
----------

This is a library used to plot graphs conveniently directly from Python. Many graph types are supported.


In [34]:
import matplotlib.pyplot as plt

In [35]:
from IPython.display import HTML
HTML('<iframe src=http://matplotlib.org/gallery.html width=700 height=350></iframe>')

In [36]:
plt.plot(x, y)
plt.title("Sample Plot")
plt.xlabel("x label")
plt.ylabel("y label");

In [37]:
plt.scatter(x, y, s=100) # press TAB after opening parenthesis to see help on `scatter`;

Pandas
======

Pandas is a library for doing data analysis in Python.  It defines DataFrame objects, and provides a lot of equivalent functions as the R data analysis library (but in Python!)

In [38]:
from IPython.display import HTML
HTML('<iframe src=http://pandas.pydata.org/ width=700 height=350></iframe>')

In [39]:
import pandas as pd
print pd.__version__

0.19.2


## Scikit-Learn

In [40]:
from IPython.display import HTML
HTML('<iframe src=http://scikit-learn.sourceforge.net/dev/auto_examples/index.html width=900 height=350></iframe>')

Easy-to use machine-learning library of algorithms with many examples and documentation.


Classification
--------------
- **Logistic Regression**
- Support Vector Machines
- Perceptron
- Decision Trees
- Random Forests
- Naive Bayes
- **Neares Neighbors**
- ...

Regression
----------
- **Linear Regression**
- Lasso
- Lars
- Ridge Regression
- Support Vector Regression
- Regression Forests
- ...

Feature Extraction
------------------
- **Principal Component Analysis**
- Independend Component Analysis
- Nonnegative Matrix Factorization
- Sparse Decomposition
- Locally Linear Embedding
- KernelPCA
- ...

Clustering
----------
- **$k$-Means**
- Mean Shift
- Spectral Clustering
- Affinity Propagation
- DBSCAN
- ...


In [41]:
%load_ext version_information

%version_information numpy, scipy, matplotlib, pandas, sklearn

Software versions
Python 2.7.13 64bit [GCC 6.3.0 20170118]
IPython 5.1.0
OS Linux 4.10.0 30 generic x86_64 with Ubuntu 17.04 zesty
numpy 1.12.1
scipy 0.18.1
matplotlib 2.0.0
pandas 0.19.2
sklearn 0.18
Fri Aug 25 10:23:40 2017 CDT

Original versions of these notebooks created by J.R. Johansson (robert@riken.jp) http://dml.riken.jp/~rob/

The latest version of this [IPython notebook](http://ipython.org/notebook.html) lecture is available at [https://bitbucket.org/dharter/intro-compsci-class](https://bitbucket.org/dharter/intro-compsci-class).