In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
plt.rcParams['figure.figsize'] = (8, 6) # set default figure size, 8in by 6in

# Video W1 12: Matrices and Vectors

[YouTube Video Link](https://www.youtube.com/watch?v=04IlpTiBTsk&index=12&list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW)

## Matrices

A matrix is a retangular array of numbers:

$$
\begin{bmatrix}
1402 &  191 \\ 
1371 &  821 \\ 
 949 & 1437 \\ 
 147 & 1448 \\ 
\end{bmatrix}
$$

The dimension of a matrix is the number of rows by the number of columns.  In the previous matrix,
we have 4 rows by 2 columns.

In Python, we use `NumPy` arrays to represent 1, 2 (and higher dimensional) vectors and matrices.

In [2]:
A = np.array([[1402, 191], [1371, 821], [949, 1437], [147, 1448]])
print(A)
print(A.shape)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
(4, 2)


We refer to entries of 2 dimensional matrices using `row,column` indices. So given:

$$
A
=
\begin{bmatrix}
1402 &  191 \\ 
1371 &  821 \\ 
 949 & 1437 \\ 
 147 & 1448 \\ 
\end{bmatrix}
$$

$$A_{ij} = i,j \; \mathrm{entry \; in \; the} \; i^{th} \; \mathrm{row,} \; j^{th} \; \mathrm{column}.$$

So

$$A_{12} = 191$$

**NOTE:** In Python, lists and `NumPy` arrays are indexed starting at 0 (0 based indexing).  This means
that when you translate any code from a 1 based mathematical indexing, to the 0 based indexing, you 
always need to subtract one.  So for example, to get the $A_{12}$ entry in our matrix we need to:

In [3]:
print(A[0,1])

191


## Vector

A vector is simply a 1 dimensional vector, or you can think of it as a matrix with n rows and 1 column:

$$
y
=
\begin{bmatrix}
460 \\ 
232 \\ 
315 \\ 
178 \\ 
\end{bmatrix}
$$

Notice that in `NumPy`, there is a slight difference between a vector, and an array with 1 column:

In [4]:
# a numpy vector is 1 dimensional, we can initialize with a 1d list
y = np.array([460, 232, 315, 178])
print(y)
print(y.shape)

# we can create a 4x1 column matrix, like this:
z = np.array([[460],
              [232],
              [315],
              [178]])
print(z)
print(z.shape)

[460 232 315 178]
(4,)
[[460]
 [232]
 [315]
 [178]]
(4, 1)


Sometimes in writing code we can use `NumPy` 1d vectors, but sometimes we need to use a $n \times 1$
column matrix instead.



# Video W1 13: Addition and Scalar Multiplication

[YouTube Video Link](https://www.youtube.com/watch?v=eCJpIfMrm6U&list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW&index=13)

## Matrix Addition

Addition and subtraction of matrices are simply element by element wise operations.  The matrices
need to have exactly the same dimensions for this to be defined:

$$
\begin{bmatrix}
1 &  0 \\ 
2 &  5 \\ 
3 & 1 \\ 
\end{bmatrix}
+
\begin{bmatrix}
4 & 0.5 \\ 
2 & 5 \\ 
0 & 1 \\ 
\end{bmatrix}
=
\begin{bmatrix}
5 & 0.5 \\ 
4 & 10 \\ 
3 & 2 \\ 
\end{bmatrix}
$$


In [5]:
A = np.array([[1, 0],
              [2, 5],
              [3, 1]])
B = np.array([[4, 0.5],
              [2, 5],
              [0, 1]])

print(A + B)
print(A - B)

[[  5.    0.5]
 [  4.   10. ]
 [  3.    2. ]]
[[-3.  -0.5]
 [ 0.   0. ]
 [ 3.   0. ]]


## Scalar Multiplication

I will probably slip into the habit of using the term scalar here and there.  Scalar is just a fancy
term for a regular, single (real valued) value.  Basically the opposite of a Matrix is a scalar value.

When you multiply (or divide) a matrix by a scalar value, you simply multiple each value in the matrix
by the scalar value:


$$
3
\times
\begin{bmatrix}
1 &  0 \\ 
2 &  5 \\ 
3 & 1 \\ 
\end{bmatrix}
=
\begin{bmatrix}
3 & 0 \\ 
6 & 15 \\ 
9 & 3 \\ 
\end{bmatrix}
$$


In [6]:
A = np.array([[1, 0],
              [2, 5],
              [3, 1]])

print(3.0 * A)
print(A / 4.0)

[[  3.   0.]
 [  6.  15.]
 [  9.   3.]]
[[ 0.25  0.  ]
 [ 0.5   1.25]
 [ 0.75  0.25]]


# Video W1 14: Matrix Vector Multiplication

[YouTube Video Link](https://www.youtube.com/watch?v=bA3wxP5AtQk&index=14&list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW)

## Example of Matrix x Vector Multiplication

$$
\begin{bmatrix}
1 &  3 \\ 
4 &  2 \\ 
2 & 1 \\ 
\end{bmatrix}
\begin{bmatrix}
1 \\ 
5 \\ 
\end{bmatrix}
=
\begin{bmatrix}
16 \\
4 \\
7 \\
\end{bmatrix}
$$

Here we multiple a $3 \times 2$ matrix by a $2 \times 1$ vector.  The result is a $3 \times 1$
vector.

In `NumPy`, the `*` operator only works to perform scalar multiplication of a matrix with a scalar
value (or scalar multiplications of two matrices of the same dimensions), thus the following
is not going to work.

In [7]:
A = np.array([[1, 3],
              [4, 2],
              [2, 1]])
B = np.array([[1],
              [5]])

print(A * B)

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

We instead need to use a `NumPy` library function if we want to do matrix multiplication:

In [8]:
np.dot(A, B)

array([[16],
       [14],
       [ 7]])

## A Neat Trick

We can compute all of the model hypothesis (given a particular $\theta_0, \theta_1$) for a number of
houses simultaneously using matrix vector multiplication.

Say our hypothesis is:

$$
h_\theta(x) = -40 + 0.25x
$$

We can do the following for a set of houses, to compute the model prices for all of the houses at the
same time:

In [9]:
X = np.array([[1, 2104],
              [1, 1416],
              [1, 1534],
              [1, 852]])
Theta = np.array([[-40],
                  [0.25]])

y = np.dot(X, Theta) # y is our hypothesis/model prices for the 4 houses of the given sizes
print(y)

[[ 486. ]
 [ 314. ]
 [ 343.5]
 [ 173. ]]


Using a vectorized matrix vector multiplication like this is much faster than doing this in a for loop.
Vectorized operations are much more computationally efficient.

# Video W1 15: Matrix Vector Multiplication

There was a duplicate in the playlist of the Matrix Vector multiplication video, so ignore W1 15.


# Video W1 16: Matrix Matrix Multiplication

[YouTube Video Link](https://www.youtube.com/watch?v=aqK2Y0l2rXE&list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW&index=16)

## Multiplying two matrices together

This is really a simple extension of the matrix by vector multiplication:

$$
\begin{bmatrix}
1 &  3 & 2 \\ 
4 &  0 & 1 \\ 
\end{bmatrix}
\begin{bmatrix}
1 & 3 \\ 
0 & 1 \\
5 & 2 \\
\end{bmatrix}
=
\begin{bmatrix}
11 & 10 \\
9  & 14 \\
\end{bmatrix}
$$

In `NumPy` we still use the same `np.dot()` function to perform matrix by matrix multiplication:

In [10]:
A = np.array([[1, 3, 2],
              [4, 0, 1]])
B = np.array([[1, 3],
              [0, 1],
              [5, 2]])

print(np.dot(A, B))

[[11 10]
 [ 9 14]]


In [11]:
# another example, a 2x2 times a 2x2 matrix
A = np.array([[1, 3],
              [2, 5]])
B = np.array([[0, 1],
              [3, 2]])

print(np.dot(A, B))

[[ 9  7]
 [15 12]]


## More Neat Tricks

Lets say instead of 1 hypothesis, we instead have 3 hypotheses that we want to calculate the predicted price for a set of houses
for:

$$
h_\theta(x) = -40 + 0.25x
$$

$$
h_\theta(x) = 200 + 0.1x
$$

$$
h_\theta(x) = -150 + 0.4x
$$


We can use matrix matrix multiplication to perform all of the prediction calculations in a single vectorized operation.


In [12]:
X = np.array([[1, 2104],
              [1, 1416],
              [1, 1534],
              [1, 852]])

Theta = np.array([[-40, 200, -150],
                  [0.25, 0.1, 0.4]])

print(np.dot(X, Theta))

[[ 486.   410.4  691.6]
 [ 314.   341.6  416.4]
 [ 343.5  353.4  463.6]
 [ 173.   285.2  190.8]]


# Video W1 17: Matrix Multiplication Properties

[YouTube Video Link](https://www.youtube.com/watch?v=00GJM2Js7AI&index=17&list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW)

A discussion of some things you should be aware when using linear algebra matrix operations.

- Matrix multipication is not commutative
- However, matrix multiplication is associative


In [13]:
# matrix multiplication is not commutative
A = np.array([[1, 1],
              [0, 0]])
B = np.array([[0, 0],
              [2, 0]])

print(np.dot(A, B))
print(np.dot(B, A))

[[2 0]
 [0 0]]
[[0 0]
 [2 2]]


In [14]:
# Matrix multiplication IS associative
C = np.array([[2, 0],
              [2, 1]])

Tmp = np.dot(A, B)
print(np.dot(Tmp, C))

Tmp = np.dot(B,C)
print(np.dot(A, Tmp))

[[4 0]
 [0 0]]
[[4 0]
 [0 0]]


## Identity Matrix

For scalar values, the value 1 is the identity, e.g $1 \times z = z \times 1 = z$.

For matrices there is an identity matrix, denotied as $I$ or $(I_{n \times n})$.  The identity matrix has 1's on the diagonal, and
zeros every else.

In [15]:
# the 4x4 identity matrix
print(np.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


For any matrix $A$,

$$
A \cdot I = I \cdot A = A
$$

In [16]:
A = np.array([[3, 4, 7],
              [1, 8, 2],
              [9, 6, 5]])

I = np.eye(3)

print(np.dot(A, I))
print(np.dot(I, A))

[[ 3.  4.  7.]
 [ 1.  8.  2.]
 [ 9.  6.  5.]]
[[ 3.  4.  7.]
 [ 1.  8.  2.]
 [ 9.  6.  5.]]


# Video W1 18: Inverse and Transpose

[YouTube Video Link](https://www.youtube.com/watch?v=9McrlFqn-gg&index=18&list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW)

The inverse of a scalar is simply the value such that when you multiple the scalar by its inverse you get 1.

For example:
$$
3 \times 3^{-1} = 3 \times \frac{1}{3} = 1
$$

For a matrix, the inverse of a matrix is a matrix such that:

$$
A \cdot (A^{-1}) = A^{-1} \cdot A = I
$$

Only square matrices can have inverses.  But not all square matrices are guaranted to have an inverse.  Finding the inverse of
a square matrix (if it exists) can be difficult.  Here is an example of a matrix and its inverse:

In [17]:
A = np.array([[3, 4],
              [2, 16]])
Ainv = np.array([[0.4, -0.1],
                 [-0.05, 0.075]])

# show that Ainv is the inverse of A
print(np.dot(A, Ainv))

[[  1.00000000e+00  -5.55111512e-17]
 [  0.00000000e+00   1.00000000e+00]]


Don't be confused if the numbers (especially the 0's), are't exactly 1 or 0, the result is very close to the Identity matrix 
(within machine precision of the calculation).

How do we compute the Inverse of a matrix?  There are algorithms to do this (of course), and it is difficult to do by hand.
The `NumPy` library has functions that can be used to compute the inverse of a matrix:

In [18]:
print(np.linalg.inv(A))

[[ 0.4   -0.1  ]
 [-0.05   0.075]]


In [19]:
print(np.dot(A, np.linalg.inv(A)))

[[ 1.  0.]
 [ 0.  1.]]


Some scalar values don't have an inverse, for example 0 doesn't have an inverse.  Likewise, some matrices don't have an inverse.
However for machine learning this is usually not an issue, because often there are pseudo inverses that are close enough for
machine learning purposes.

## Matrix Transpose

The transpose of matrix simply flips the row and column indexes of a matrix:

$$
A =
\begin{bmatrix}
1 &  2 & 0 \\ 
3 &  5 & 9 \\ 
\end{bmatrix}
\;\;\;
A^T =
\begin{bmatrix}
1 &  3 \\ 
2 &  5\\
0 & 9 \\
\end{bmatrix}
$$

In [20]:
A = np.array([[1, 2, 0],
              [3, 5, 9]])
print(np.transpose(A))
print(A.T) # we can use the transpose function, or the convenience x.T attribute, to transpose

[[1 3]
 [2 5]
 [0 9]]
[[1 3]
 [2 5]
 [0 9]]


In [21]:
%load_ext version_information

%version_information numpy, scipy, matplotlib, pandas, sklearn

Software versions
Python 3.6.1 64bit [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
IPython 6.4.0
OS Linux 4.13.0 46 generic x86_64 with debian stretch sid
numpy 1.12.1
scipy 0.19.0
matplotlib 2.0.2
pandas 0.20.1
sklearn 0.18.1
Sat Aug 25 09:31:23 2018 CDT